# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
#
# Copyright (C) 2015 Sergio Conde Gomez, Cristina Hermoso Garcia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |c|
  c.vm.box = "ubuntu/trusty64"

  c.vm.provider :virtualbox do |v|
    v.name = "Arquitectura del Data Warehouse - Prueba MonetDB"

    v.customize ["modifyvm", :id, "--ioapic", "on"  ]
    v.customize ["modifyvm", :id, "--cpus"  , "2"   ]
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  c.vm.synced_folder "../DB/", "/DB/", create: true, owner: "vagrant", group: "vagrant"

  c.vm.provision :shell, run: "once", privileged: true, preserve_order: true, path: "deploy.sh"
end
